name: simple_chat
description: Simple chat application utilizing Xmpp Stone library

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  xmpp_stone:
    git:
      url: https://github.com/vukoye/xmpp_dart
      ref: master

  synchronized: ^3.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  get_it: ^6.0.0
  sqflite: ^2.0.0
  shared_preferences: ^2.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
